### ISSUE TITLE
Fetch validator status script error 

### ISSUE THREAD

**Issue by mrkaurelius** [hyperledger/indy-node-monitor#68]
Older version of python and missing dependency causes error on `run.sh`

```
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    monitor_plugins = PluginCollection('plugins')
  File "/home/indy/plugin_collection.py", line 69, in __init__
    self.reload_plugins()
  File "/home/indy/plugin_collection.py", line 78, in reload_plugins
    self.walk_package(self.plugin_package)
  File "/home/indy/plugin_collection.py", line 126, in walk_package
    self.walk_package(package + '.' + child_pkg)
  File "/home/indy/plugin_collection.py", line 100, in walk_package
    plugin_module = __import__(pluginname, fromlist=['blah'])
  File "/home/indy/plugins/metrics/google_sheets.py", line 3, in <module>
    import gspread
  File "/home/indy/.local/lib/python3.7/site-packages/gspread/__init__.py", line 7, in <module>
    from .auth import (
  File "/home/indy/.local/lib/python3.7/site-packages/gspread/auth.py", line 19, in <module>
    from .client import Client
  File "/home/indy/.local/lib/python3.7/site-packages/gspread/client.py", line 17, in <module>
    from .spreadsheet import Spreadsheet
  File "/home/indy/.local/lib/python3.7/site-packages/gspread/spreadsheet.py", line 15, in <module>
    from .worksheet import Worksheet
  File "/home/indy/.local/lib/python3.7/site-packages/gspread/worksheet.py", line 11, in <module>
    from typing import (
ImportError: cannot import name 'Literal' from 'typing' (/usr/lib/python3.7/typing.py)
```

**Comment by mrkaurelius** [comment]
This PR could be helpful #69
